
import { MissionLevel, ShopItem, ItemCategory, Achievement, Player } from './types';

export const XP_PER_LEVEL = 200;

export const INITIAL_PLAYERS: Player[] = [
  {
    name: 'Leo',
    avatar: 'https://i.postimg.cc/DmwHTpg9/Generated-Image-September-18-2025-11-42-AM.png',
    level: 1,
    xp: 0,
    coins: 50,
    ownedItems: [],
    equippedItems: {},
    achievements: [],
    missionHistory: {},
  },
  {
    name: 'Vale',
    avatar: 'https://i.postimg.cc/svtN5jrz/Generated-Image-September-18-2025-11-38-AM.png',
    level: 1,
    xp: 0,
    coins: 50,
    ownedItems: [],
    equippedItems: {},
    achievements: [],
    missionHistory: {},
  },
];


export const LEVELS: MissionLevel[] = [
  // Math Levels
  {
    id: 'tables_2',
    name: 'Tablas del 2',
    levelNumber: 1,
    requiredLevel: 1,
    xpReward: 100,
    coinReward: 20,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 2 x 3?', options: ['4', '8', '6', '5'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 2 x 7?', options: ['12', '14', '16', '18'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 2 x 1?', options: ['3', '2', '1', '4'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 2 x 9?', options: ['18', '20', '16', '22'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 2 x 5?', options: ['8', '12', '15', '10'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 2 x 2?', options: ['4', '6', '2', '8'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 2 x 8?', options: ['14', '18', '16', '20'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 2 x 4?', options: ['6', '8', '10', '12'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 2 x 6?', options: ['12', '10', '14', '16'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 2 x 10?', options: ['18', '22', '10', '20'], correctAnswerIndex: 3 },
    ],
  },
  {
    id: 'tables_5',
    name: 'Tablas del 5',
    levelNumber: 2,
    requiredLevel: 2,
    xpReward: 100,
    coinReward: 20,
    hasBubbleGame: true,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 5 x 2?', options: ['10', '15', '5', '20'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 5 x 5?', options: ['20', '30', '25', '35'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 5 x 8?', options: ['35', '40', '45', '50'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 5 x 1?', options: ['10', '0', '1', '5'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 5 x 9?', options: ['45', '40', '50', '35'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 5 x 3?', options: ['10', '15', '20', '25'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 5 x 7?', options: ['30', '40', '35', '25'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 5 x 4?', options: ['20', '15', '25', '30'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 5 x 6?', options: ['25', '35', '20', '30'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 5 x 10?', options: ['40', '50', '60', '45'], correctAnswerIndex: 1 },
    ],
  },
    {
    id: 'tables_10',
    name: 'Tablas del 10',
    levelNumber: 3,
    requiredLevel: 3,
    xpReward: 100,
    coinReward: 20,
    timeLimit: 8,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 10 x 4?', options: ['40', '30', '50', '14'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 10 x 7?', options: ['60', '80', '70', '17'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 10 x 2?', options: ['12', '20', '30', '22'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 10 x 9?', options: ['19', '99', '109', '90'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 10 x 1?', options: ['10', '11', '101', '1'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 10 x 5?', options: ['40', '50', '60', '15'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 10 x 8?', options: ['70', '90', '80', '18'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 10 x 3?', options: ['30', '13', '20', '40'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 10 x 6?', options: ['50', '70', '16', '60'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 10 x 10?', options: ['1000', '100', '20', '110'], correctAnswerIndex: 1 },
    ],
  },
  {
    id: 'boss_mission_1',
    name: 'Reto Mixto',
    levelNumber: 4,
    requiredLevel: 4,
    xpReward: 150,
    coinReward: 50,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 2 x 8?', options: ['14', '16', '18', '20'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 5 x 7?', options: ['30', '40', '35', '25'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 10 x 3?', options: ['30', '13', '20', '40'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 2 x 4?', options: ['6', '8', '10', '12'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 5 x 9?', options: ['45', '40', '50', '35'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 10 x 10?', options: ['1000', '100', '20', '110'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 2 x 1?', options: ['3', '2', '1', '4'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 10 x 5?', options: ['40', '50', '60', '15'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 5 x 3?', options: ['10', '15', '20', '25'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 2 x 9?', options: ['18', '20', '16', '22'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 10 x 6?', options: ['50', '70', '16', '60'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 5 x 5?', options: ['20', '30', '25', '35'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 2 x 6?', options: ['12', '10', '14', '16'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 5 x 10?', options: ['40', '50', '60', '45'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 10 x 8?', options: ['70', '90', '80', '18'], correctAnswerIndex: 2 },
    ],
  },
  {
    id: 'tables_3',
    name: 'Tablas del 3',
    levelNumber: 5,
    requiredLevel: 5,
    xpReward: 100,
    coinReward: 20,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 3 x 4?', options: ['9', '12', '15', '6'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 3 x 7?', options: ['21', '24', '18', '20'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 3 x 2?', options: ['9', '3', '6', '8'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 3 x 9?', options: ['24', '30', '21', '27'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 3 x 5?', options: ['15', '12', '18', '20'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 3 x 1?', options: ['1', '3', '6', '4'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 3 x 8?', options: ['21', '27', '24', '30'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 3 x 3?', options: ['6', '12', '9', '3'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 3 x 6?', options: ['18', '15', '21', '12'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 3 x 10?', options: ['20', '33', '30', '40'], correctAnswerIndex: 2 },
    ],
  },
  {
    id: 'tables_6',
    name: 'Tablas del 6',
    levelNumber: 6,
    requiredLevel: 6,
    xpReward: 100,
    coinReward: 20,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 6 x 2?', options: ['18', '6', '12', '16'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 6 x 5?', options: ['30', '36', '24', '40'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 6 x 8?', options: ['42', '48', '54', '46'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 6 x 3?', options: ['12', '24', '18', '20'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 6 x 7?', options: ['49', '36', '48', '42'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 6 x 4?', options: ['24', '30', '18', '28'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 6 x 9?', options: ['54', '60', '48', '56'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 6 x 6?', options: ['30', '42', '36', '48'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 6 x 1?', options: ['1', '7', '16', '6'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 6 x 10?', options: ['60', '16', '70', '50'], correctAnswerIndex: 0 },
    ],
  },
  {
    id: 'tables_9',
    name: 'Tablas del 9',
    levelNumber: 7,
    requiredLevel: 7,
    xpReward: 100,
    coinReward: 20,
    timeLimit: 10,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 9 x 3?', options: ['18', '27', '36', '21'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 9 x 5?', options: ['45', '54', '36', '40'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 9 x 8?', options: ['81', '63', '72', '80'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 9 x 2?', options: ['18', '27', '16', '20'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 9 x 7?', options: ['54', '72', '56', '63'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 9 x 4?', options: ['36', '45', '27', '32'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 9 x 9?', options: ['81', '90', '72', '99'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 9 x 6?', options: ['45', '63', '54', '60'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 9 x 1?', options: ['10', '19', '1', '9'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 9 x 10?', options: ['100', '90', '99', '19'], correctAnswerIndex: 1 },
    ],
  },
  {
    id: 'boss_mission_2',
    name: 'Reto Mixto 2',
    levelNumber: 8,
    requiredLevel: 8,
    xpReward: 150,
    coinReward: 50,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 3 x 8?', options: ['21', '24', '27', '30'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 6 x 7?', options: ['36', '48', '42', '49'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 9 x 5?', options: ['45', '54', '36', '40'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 3 x 4?', options: ['9', '12', '15', '18'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 9 x 9?', options: ['81', '72', '90', '99'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 6 x 2?', options: ['10', '14', '18', '12'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 9 x 3?', options: ['18', '36', '27', '24'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 3 x 6?', options: ['18', '15', '21', '12'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 6 x 8?', options: ['42', '48', '54', '56'], correctAnswerIndex: 1 },
    ],
  },
  {
    id: 'tables_7',
    name: 'Tablas del 7',
    levelNumber: 9,
    requiredLevel: 9,
    xpReward: 100,
    coinReward: 20,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 7 x 2?', options: ['14', '21', '16', '28'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 7 x 5?', options: ['30', '42', '35', '40'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 7 x 8?', options: ['49', '56', '63', '54'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 7 x 3?', options: ['21', '28', '14', '24'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 7 x 7?', options: ['42', '56', '48', '49'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 7 x 4?', options: ['28', '35', '21', '32'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 7 x 9?', options: ['63', '70', '56', '72'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 7 x 6?', options: ['35', '49', '42', '48'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 7 x 1?', options: ['8', '17', '1', '7'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 7 x 10?', options: ['77', '70', '80', '60'], correctAnswerIndex: 1 },
    ],
  },
  {
    id: 'tables_8',
    name: 'Tablas del 8',
    levelNumber: 10,
    requiredLevel: 10,
    xpReward: 100,
    coinReward: 20,
    subject: 'math',
    questions: [
      { text: '¿Cuánto es 8 x 3?', options: ['16', '24', '32', '21'], correctAnswerIndex: 1 },
      { text: '¿Cuánto es 8 x 5?', options: ['40', '48', '32', '45'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 8 x 8?', options: ['72', '56', '64', '80'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 8 x 2?', options: ['16', '24', '18', '20'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 8 x 7?', options: ['48', '64', '49', '56'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 8 x 4?', options: ['32', '40', '24', '36'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 8 x 9?', options: ['72', '81', '64', '80'], correctAnswerIndex: 0 },
      { text: '¿Cuánto es 8 x 6?', options: ['40', '54', '48', '56'], correctAnswerIndex: 2 },
      { text: '¿Cuánto es 8 x 1?', options: ['9', '18', '1', '8'], correctAnswerIndex: 3 },
      { text: '¿Cuánto es 8 x 10?', options: ['88', '80', '90', '18'], correctAnswerIndex: 1 },
    ],
  },
  // History Levels
  {
    id: 'history_mochica',
    name: 'Cultura Mochica',
    levelNumber: 1,
    requiredLevel: 1,
    xpReward: 50,
    coinReward: 15,
    subject: 'history',
    questions: [
      { text: '¿Cómo se llamaba el dios principal de los mochicas, también conocido como "El Degollador"?', options: ['Inti', 'Wiracocha', 'Ai Apaec', 'Pachacamac'], correctAnswerIndex: 2 },
      { text: 'En 1987 se descubrió la tumba de un famoso gobernante mochica con grandes tesoros. ¿Quién era?', options: ['El Señor de Sipán', 'El Inca Pachacútec', 'La Dama de Cao', 'El Rey Túpac'], correctAnswerIndex: 0 },
      { text: 'Los mochicas eran famosos por su cerámica, especialmente por los vasos que mostraban rostros humanos. ¿Cómo se llaman?', options: ['Keros', 'Huacos Retratos', 'Cántaros de Piedra', 'Vasijas de Oro'], correctAnswerIndex: 1 },
      { text: 'Además de reyes, los arqueólogos descubrieron la tumba de una poderosa gobernante mochica. ¿Cuál es su nombre?', options: ['La Reina de Saba', 'La Sacerdotisa de Moro', 'La Dama de Cao', 'La Emperatriz de Moche'], correctAnswerIndex: 2 },
      { text: 'La cultura Mochica se desarrolló principalmente en la costa de un país. ¿Cuál?', options: ['Chile', 'Ecuador', 'Colombia', 'Perú'], correctAnswerIndex: 3 },
    ]
  },
  {
    id: 'history_chimu',
    name: 'Cultura Chimú',
    levelNumber: 2,
    requiredLevel: 2,
    xpReward: 50,
    coinReward: 15,
    subject: 'history',
    questions: [
      { text: '¿Cuál fue la impresionante capital de la cultura Chimú, hecha de barro y la más grande de América?', options: ['Cusco', 'Caral', 'Machu Picchu', 'Chan Chan'], correctAnswerIndex: 3 },
      { text: 'Los Chimú eran grandes agricultores gracias a los sistemas que heredaron de los mochicas. ¿Qué sistemas eran?', options: ['Terrazas flotantes', 'Sistemas de irrigación', 'Invernaderos de paja', 'Cultivos en la selva'], correctAnswerIndex: 1 },
      { text: '¿Cuál era uno de los dioses más importantes para la cultura Chimú?', options: ['El Sol', 'La Luna', 'La Montaña', 'El Río'], correctAnswerIndex: 1 },
      { text: 'Para regar sus cultivos en el desierto, los Chimú usaban una técnica especial para sacar agua de la tierra. ¿Cómo se llamaba?', options: ['Acueductos romanos', 'Pozos de los deseos', 'Los wachaques', 'Canales de Venecia'], correctAnswerIndex: 2 },
      { text: 'La increíble ciudad de Chan Chan se encuentra en la costa norte de Perú, cerca de una ciudad moderna. ¿Cuál es?', options: ['Lima', 'Arequipa', 'Trujillo', 'Iquitos'], correctAnswerIndex: 2 },
    ]
  },
  {
    id: 'history_tiahuanaco',
    name: 'Cultura Tiahuanaco',
    levelNumber: 3,
    requiredLevel: 3,
    xpReward: 50,
    coinReward: 15,
    subject: 'history',
    questions: [
      { text: 'La cultura Tiahuanaco se desarrolló en una zona muy alta, cerca de un famoso lago. ¿Qué lago es?', options: ['Lago de Maracaibo', 'Lago Titicaca', 'Lago de Pátzcuaro', 'Laguna de la Huacachina'], correctAnswerIndex: 1 },
      { text: '¿Cómo se llama el vaso ceremonial de madera, a veces con decoraciones, que era muy importante para los Tiahuanaco?', options: ['Cántaro', 'Botella', 'Quero', 'Copa'], correctAnswerIndex: 2 },
      { text: 'Para construir sus templos y palacios, como el de Kalasasaya, los Tiahuanaco usaban grandes bloques de...', options: ['Madera', 'Ladrillos de barro', 'Piedra', 'Hielo'], correctAnswerIndex: 2 },
      { text: 'La cultura Tiahuanaco se desarrolló al mismo tiempo que otra gran cultura andina. ¿Cuál fue?', options: ['Los Incas', 'Los Mochicas', 'La cultura Huari', 'Los Mayas'], correctAnswerIndex: 2 },
      { text: 'El monumento más famoso de Tiahuanaco es una gigante puerta de piedra con un dios tallado. ¿Cómo se le conoce?', options: ['La Puerta del Cielo', 'El Arco del Triunfo', 'La Portada del Sol', 'El Muro de los Lamentos'], correctAnswerIndex: 2 },
    ]
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'hat_wizard', name: 'Sombrero Mago', price: 120, category: ItemCategory.Hat, imageUrl: 'https://i.imgur.com/LMMR67I.png' },
  { id: 'mask_blue', name: 'Antifaz Azul', price: 50, category: ItemCategory.Accessory, imageUrl: 'https://i.imgur.com/Jd3NE4b.png' },
  { id: 'mask_red', name: 'Antifaz Rojo', price: 50, category: ItemCategory.Accessory, imageUrl: 'https://i.imgur.com/M6iJ2Ct.png' },
  { id: 'mask_green', name: 'Antifaz Verde', price: 50, category: ItemCategory.Accessory, imageUrl: 'https://i.imgur.com/yP8Yf74.png' },
  { id: 'mask_hero', name: 'Antifaz Héroe', price: 120, category: ItemCategory.Accessory, imageUrl: 'https://i.imgur.com/G9yV2B5.png' },
  { id: 'glasses_3d', name: 'Gafas 3D', price: 120, category: ItemCategory.Accessory, imageUrl: 'https://i.imgur.com/wNPmSjA.png' },
  { id: 'hat_party', name: 'Gorro Fiesta', price: 120, category: ItemCategory.Hat, imageUrl: 'https://i.imgur.com/L13DkQH.png' },
];

export const ACHIEVEMENTS: Achievement[] = [
    { id: 'basic_tables_master', name: 'Maestro de Tablas Básicas', description: 'Dominaste las tablas del 2, 5 y 10', icon: '🏆' },
    { id: 'master_of_2', name: 'Maestro del 2', description: 'Completaste la tabla del 2', icon: '🚀' },
    { id: 'math_rocket', name: 'Cohete Matemático', description: '5 misiones sin fallos', icon: '⭐' },
    { id: 'csv_pro', name: 'Usbio a Cstvfds', description: 'Completaste tabla la 50 problemas', icon: '🛡️' },
    { id: 'doro_pro', name: 'Dorovts Folt Uocl', description: 'Rsscl 50 problemas', icon: '🎩' },
    { id: 'easy_peasy', name: 'Diurs de Faciles', description: 'Sua cox l lista do dale', icon: '🧙' },
    { id: 'fowdel', name: 'Fowdel Hal ie', description: 'Complas la bila on asaats por eitais', icon: '📜' },
    { id: 'seu_pro', name: 'Seuppl ds', description: 'reorta regoation', icon: '📐' },
];